In [1]:
import numpy as np
import pandas as pd
import difflib as dfl
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
data_1=pd.read_csv("C:\\Users\\HP\\Downloads\\song_data.csv")
data_1.head(50)

song_id                                              title  \
0   SOQMMHC12AB0180CB8                                       Silent Night   
1   SOVFVAK12A8C1350D9                                        Tanssi vaan   
2   SOGTUKN12AB017F4F1                                  No One Could Ever   
3   SOBNYVR12A8C13558C                                      Si Vos Querés   
4   SOHSBXH12A8C13B0DF                                   Tangle Of Aspens   
5   SOZVAPQ12A8C13B63C  Symphony No. 1 G minor "Sinfonie Serieuse"/All...   
6   SOQVRHI12A6D4FB2D7                                   We Have Got Love   
7   SOEYRFT12AB018936C                                  2 Da Beat Ch'yall   
8   SOPMIYT12A6D4F851E                                            Goodbye   
9   SOJCFMH12A8C13B0C2                         Mama_ mama can't you see ?   
10  SOYGNWH12AB018191E                                      L'antarctique   
11  SOLJTLX12AB01890ED                                 El hijo del pueblo   
12  SOQQESG12A58A7AA28                Cold Beer feat. Prince Metropolitan   
13  SOMPVQB12A8C1379BB                                             Pilots   
14  SOGPCJI12A8C13CCA0                                             N Gana   
15  SOSDCFG12AB0184647                                                006   
16  SOBARPM12A8C133DFF                (Looking For) The Heart Of Saturday   
17  SOKOVRQ12A8C142811                                  Ethos of Coercion   
18  SOIMMJJ12AF72AD643                                        Rock-N-Rule   
19  SOVMBTP12A8C13A8F6                                      La bola extra   
20  SOOUESZ12AB0189AFD                                     I Made It Over   
21  SOAGMGG12A6D4F9099      Debussy : 12 Etudes : VI Pour les huit doigts   
22  SOGFWVT12A8C137C64                                            Nervous   
23  SOKLPMH12AB01861FA                                     In The Journey   
24  SOEPAIN12A8C1396A7                          Fuckin Ethic People (999)   
25  SOQMZZI12AB01850D4                                 Tu Vida Con La Mía   
26  SOEEHEY12CF5F88FB4                                          I'm Ready   
27  SOWUMAZ12A67ADE769                                     Take As Needed   
28  SOJJAZT12AC4687219              Autumn In The Mind (Acoustic Version)   
29  SOMLHJQ12AC4685B45                                            Tequila   
30  SOYNOIK12A6D4F7F3F       All For A Purpose (Speak Life Album Version)   
31  SOPUJOM12AB017FEEB                                               C On   
32  SOGNNYL12A6D4F910B                       Raspberry Beret (LP Version)   
33  SOOLRHW12A8C142643                              All of the same blood   
34  SOMKNZS12A8C13DEBC                              One Little Too Little   
35  SOYKVON12A8C14097E                                 Cockleshell Heroes   
36  SOEXAWC12AB01817E6                                     Trancesequence   
37  SOKQCDA12A6D4FA556                                    Wonderful Stash   
38  SOFWVLR12A8C1328DC                                            La filo   
39  SOLRKBF12A8C13C88A                                      Throw It Away   
40  SOBDLRM12A8C13A0AC                                Before He Kissed Me   
41  SOMXBRA12AB017C656                                            Blessed   
42  SODJAOH12A58A77B23                                      Goa Amsterdam   
43  SOCPTIN12A8C14265F                            Disaster [Demo Version]   
44  SODVOFJ12AB0181EE6                                      Night And Day   
45  SODDEQU12AAF3B2FC8                                           Passione   
46  SONYUEW12AB018B373     My Everything [Screwed] (feat. Trae The Truth)   
47  SOWWQXA12A81C1F9CA                                             Scream   
48  SONNHYN12AB018538B                                   The Man Delusion   
49  SOCWWYB12A6D4F9AF4   He Is Not Silent (Out Of The Grey Album Version)   

                                   release  \
0                    Monster Ballads X-Ma

In [3]:
data_2=pd.read_csv("C:\\Users\\HP\\Downloads\\triplets_file.csv")
data_2.head(50)

user_id             song_id  listen_count
0   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995             1
1   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBBMDR12A8C13253B             2
2   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBXHDL12A81C204C0             1
3   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBYHAJ12A6701BF1D             1
4   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODACBL12A8C13C273             1
5   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODDNQT12A6D4F5F7E             5
6   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODXRTY12AB0180F3B             1
7   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOFGUAY12AB017B0A8             1
8   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOFRQTD12A81C233C0             1
9   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOHQWYZ12A6D4FA701             1
10  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOIYTOA12A6D4F9A23             1
11  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOIZAZL12A6701C53B             5
12  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOJNNUA12A8AE48C7A             1
13  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOJPFQG12A58A7833A             1
14  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOKRIMP12A6D4F5DA3             5
15  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOLLGNU12AF72A4D4F             1
16  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOMGIYR12AB0187973             6
17  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOMLMKI12A81C204BC             1
18  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOMSQJY12A8C138539             1
19  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SONSAEZ12A8C138D7A             1
20  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOOKGRB12A8C13CD66             1
21  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOPCVQE12AC468AF36             1
22  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOQIVUD12AB01821D2             1
23  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOQJLDY12AAF3B456D             1
24  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOQLCKR12A81C22440             1
25  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SORPMYJ12AF729EB90             1
26  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SORQHCG12A58A7EEBA             1
27  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SORUFVF12AB018230B             1
28  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SORWLTW12A670208FA             1
29  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SORZASF12A6D4F8CFA             2
30  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOSYBEV12AB0182933             1
31  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOTFATN12A6D4FA74D             1
32  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOTLVCL12AB0182D22             1
33  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOTRSFZ12A8C142BF6             1
34  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOUKXIN12A8C133C7F             1
35  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOVHRGF12A8C13852F             1
36  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOVQEYZ12A8C1379D8             1
37  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOVYIYI12A8C138D88             1
38  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOWQLXP12AF72A08A2             1
39  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOWSPUS12AC468BEE3             1
40  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOXMIUS12A8C13CD59             1
41  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOXRXDG12A8C131DE5             1
42  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOXZQDE12A8C135833             1
43  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOYHEPA12A8C13097F             8
44  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOZOBWN12A8C130999             1
45  85c1f87fea955d09b4bec2e36aee110927aedf9a  SODJTHN12AF72A8FCD             2
46  bd4c6e843f00bd476847fb75c47b4fb430a06856  SOBDRND12A8C13FD08             1
47  bd4c6e843f00bd476847fb75c47b4fb430a06856  SOCHBAJ12AAF3B3A4F             1
48  bd4c6e843f00bd476847fb75c47b4fb430a06856  SOCZTMT12AF72A078E             1
49  bd4c6e843f00bd476847fb75c47b4fb430a06856  SOHRQZQ12A6D4F81D2             1

In [5]:
data_3 = pd.merge(data_2, data_1.drop_duplicates(['song_id']), on='song_id', how='left')
display (data_3.shape)
display (data_3.head(50))


(2000000, 7)

user_id             song_id  \
0   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995   
1   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBBMDR12A8C13253B   
2   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBXHDL12A81C204C0   
3   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBYHAJ12A6701BF1D   
4   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODACBL12A8C13C273   
5   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODDNQT12A6D4F5F7E   
6   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODXRTY12AB0180F3B   
7   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOFGUAY12AB017B0A8   
8   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOFRQTD12A81C233C0   
9   b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOHQWYZ12A6D4FA701   
10  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOIYTOA12A6D4F9A23   
11  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOIZAZL12A6701C53B   
12  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOJNNUA12A8AE48C7A   
13  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOJPFQG12A58A7833A   
14  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOKRIMP12A6D4F5DA3   
15  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOLLGNU12AF72A4D4F   
16  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOMGIYR12AB0187973   
17  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOMLMKI12A81C204BC   
18  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOMSQJY12A8C138539   
19  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SONSAEZ12A8C138D7A   
20  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOOKGRB12A8C13CD66   
21  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOPCVQE12AC468AF36   
22  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOQIVUD12AB01821D2   
23  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOQJLDY12AAF3B456D   
24  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOQLCKR12A81C22440   
25  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SORPMYJ12AF729EB90   
26  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SORQHCG12A58A7EEBA   
27  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SORUFVF12AB018230B   
28  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SORWLTW12A670208FA   
29  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SORZASF12A6D4F8CFA   
30  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOSYBEV12AB0182933   
31  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOTFATN12A6D4FA74D   
32  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOTLVCL12AB0182D22   
33  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOTRSFZ12A8C142BF6   
34  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOUKXIN12A8C133C7F   
35  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOVHRGF12A8C13852F   
36  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOVQEYZ12A8C1379D8   
37  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOVYIYI12A8C138D88   
38  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOWQLXP12AF72A08A2   
39  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOWSPUS12AC468BEE3   
40  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOXMIUS12A8C13CD59   
41  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOXRXDG12A8C131DE5   
42  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOXZQDE12A8C135833   
43  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOYHEPA12A8C13097F   
44  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOZOBWN12A8C130999   
45  85c1f87fea955d09b4bec2e36aee110927aedf9a  SODJTHN12AF72A8FCD   
46  bd4c6e843f00bd476847fb75c47b4fb430a06856  SOBDRND12A8C13FD08   
47  bd4c6e843f00bd476847fb75c47b4fb430a06856  SOCHBAJ12AAF3B3A4F   
48  bd4c6e843f00bd476847fb75c47b4fb430a06856  SOCZTMT12AF72A078E   
49  bd4c6e843f00bd476847fb75c47b4fb430a06856  SOHRQZQ12A6D4F81D2   

    listen_count                                              title  \
0              1                                           The Cove   
1              2                                    Entre Dos Aguas   
2              1                                           Stronger   
3              1                                     Constellations   
4              1                                       Learn To Fly   
5              5                       Apuesta Por El Rock 'N' Roll   
6              1                                      Paper Gangsta   


In [7]:
data_3=data_3.head(60000)
data_3.shape

(60000, 7)

In [8]:
data_3['song'] = data_3['title']+' - '+data_3['artist_name']
data_3.head()


user_id             song_id  listen_count  \
0  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995             1   
1  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBBMDR12A8C13253B             2   
2  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBXHDL12A81C204C0             1   
3  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBYHAJ12A6701BF1D             1   
4  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODACBL12A8C13C273             1   

             title                        release    artist_name  year  \
0         The Cove             Thicker Than Water   Jack Johnson     0   
1  Entre Dos Aguas            Flamenco Para Niños  Paco De Lucia  1976   
2         Stronger                     Graduation     Kanye West  2007   
3   Constellations              In Between Dreams   Jack Johnson  2005   
4     Learn To Fly  There Is Nothing Left To Lose   Foo Fighters  1999   

                              song  
0          The Cove - Jack Johnson  
1  Entre Dos Aguas - Paco De Lucia  
2            Stronger - Kanye West  
3    Constellations - Jack Johnson  
4      Learn To Fly - Foo Fighters

In [9]:
song_grouped = data_3.groupby(['song']).agg({'listen_count':'count'}).reset_index()
song_grouped.head()


song  listen_count
0  #!*@ You Tonight [Featuring R. Kelly] (Explici...             1
1                           #40 - DAVE MATTHEWS BAND             7
2                                & Down - Boys Noize            14
3                          ' Cello Song - Nick Drake             3
4                        '97 Bonnie & Clyde - Eminem             6

In [10]:
grouped_sum = song_grouped['listen_count'].sum()
grouped_sum


60000

In [11]:
song_grouped['percentage'] = (song_grouped['listen_count'] / grouped_sum ) * 100
song_grouped.sort_values(['listen_count', 'song'], ascending=[0,1])

song  listen_count  \
6847                           Sehr kosmisch - Harmonia           252   
8716                                       Undo - Björk           232   
1987  Dog Days Are Over (Radio Edit) - Florence + Th...           222   
9482                     You're The One - Dwight Yoakam           203   
6507                            Revelry - Kings Of Leon           202   
...                                                 ...           ...   
9507  Your Mother's Here To Stay  (LP Version) - All...             1   
9516                    Your Time Has Come - Audioslave             1   
9537                                clouding - Four Tet             1   
9538                              high fives - Four Tet             1   
9547                               the Love Song - K-OS             1   

      percentage  
6847    0.420000  
8716    0.386667  
1987    0.370000  
9482    0.338333  
6507    0.336667  
...          ...  
9507    0.001667  
9516    0.001667  
9537    0.001667  
9538    0.001667  
9547    0.001667  

[9551 rows x 3 columns]

In [13]:
combined_features = song_grouped['song']+' '+str(song_grouped['listen_count'])+' '+str(song_grouped['percentage'])
display (combined_features)

0       #!*@ You Tonight [Featuring R. Kelly] (Explici...
1       #40 - DAVE MATTHEWS BAND 0        1\n1        ...
2       & Down - Boys Noize 0        1\n1        7\n2 ...
3       ' Cello Song - Nick Drake 0        1\n1       ...
4       '97 Bonnie & Clyde - Eminem 0        1\n1     ...
                              ...                        
9546    sun drums and soil - Four Tet 0        1\n1   ...
9547    the Love Song - K-OS 0        1\n1        7\n2...
9548    you were there with me - Four Tet 0        1\n...
9549    ¿Lo Ves? [Piano Y Voz] - Alejandro Sanz 0     ...
9550    Época - Gotan Project 0        1\n1        7\n...
Name: song, Length: 9551, dtype: object

In [14]:
vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combined_features)
display (feature_vectors.shape)
print (feature_vectors)

(9551, 10344)

  (0, 3492)	0.057499510050270736
  (0, 6930)	0.057499510050270736
  (0, 2)	0.11499902010054147
  (0, 4)	0.11499902010054147
  (0, 6)	0.057499510050270736
  (0, 3)	0.057499510050270736
  (0, 8)	0.057499510050270736
  (0, 7)	0.057499510050270736
  (0, 1)	0.11499902010054147
  (0, 4595)	0.057499510050270736
  (0, 2867)	0.11499902010054147
  (0, 127)	0.11499902010054147
  (0, 5265)	0.11499902010054147
  (0, 5362)	0.057499510050270736
  (0, 6305)	0.11499902010054147
  (0, 126)	0.11499902010054147
  (0, 125)	0.11499902010054147
  (0, 124)	0.11499902010054147
  (0, 123)	0.11499902010054147
  (0, 122)	0.11499902010054147
  (0, 27)	0.057499510050270736
  (0, 6508)	0.38340663378059026
  (0, 9218)	0.1422664271166194
  (0, 9784)	0.18230638605221408
  (0, 305)	0.19474274702407415
  :	:
  (9549, 27)	0.04557890389843305
  (9550, 10340)	0.5988475820186061
  (9550, 3934)	0.48555962991138485
  (9550, 7261)	0.42159892670202653
  (9550, 3492)	0.06322720993126894
  (9550, 6930)	0.06322720993126894
  (9550,

In [15]:
similarity = cosine_similarity(feature_vectors)
print  (similarity )

[[1.         0.19640588 0.24344505 ... 0.2367822  0.14938358 0.20722541]
 [0.19640588 1.         0.25371859 ... 0.19725702 0.15568767 0.21597046]
 [0.24344505 0.25371859 1.         ... 0.24450004 0.19297484 0.26769535]
 ...
 [0.2367822  0.19725702 0.24450004 ... 1.         0.15003095 0.20812344]
 [0.14938358 0.15568767 0.19297484 ... 0.15003095 1.         0.16426413]
 [0.20722541 0.21597046 0.26769535 ... 0.20812344 0.16426413 1.        ]]


In [16]:
similarity.shape

(9551, 9551)

In [17]:
song_name = input(' Enter song name with its artist: ')

 Enter song name with its artist: Sehr kosmisch - Harmonia


In [18]:
all_titles = list(data_3['title'])
print(all_titles)

['The Cove', 'Entre Dos Aguas', 'Stronger', 'Constellations', 'Learn To Fly', "Apuesta Por El Rock 'N' Roll", 'Paper Gangsta', 'Stacked Actors', 'Sehr kosmisch', "Heaven's gonna burn your eyes", 'Let It Be Sung', "I'll Be Missing You (Featuring Faith Evans & 112)(Album Version)", 'Love Shack', 'Clarity', "I?'m A Steady Rollin? Man", 'The Old Saloon', 'Behind The Sea [Live In Chicago]', 'Champion', 'Breakout', 'Ragged Wood', 'Mykonos', 'Country Road', 'Oh No', 'Love Song For No One', 'Jewels And Gold', 'Warning', '83', 'Neon', 'The Middle', 'High and dry', 'All That We Perceive', 'The Christmas Song  (LP Version)', 'Our Swords (Soundtrack Version)', 'Are You In?', 'Drive', 'Generator', 'Come Back To Bed', "He Doesn't Know Why", 'Trani', "Bigger Isn't Better", 'Sun Giant', 'City Love', 'Right Back', 'Moonshine', 'Holes To Heaven', 'The Best of Times', 'Sun Hands', 'Camera Talk', 'Belle', 'Auto Rock', 'Who Knows Who Cares', 'Girlfriend', 'Armistice', 'Swimming In The Flood', 'Streets On L

In [20]:

find_close_match = dfl.get_close_matches(song_name,all_titles)
print(find_close_match)

['Sehr kosmisch', 'Sehr kosmisch', 'Sehr kosmisch']


In [21]:
close_match = find_close_match[0]
print(close_match)

Sehr kosmisch


In [27]:
song_index = data_3[data_3.title == close_match]['year'].values[0]

similarity_score = list(enumerate(similarity[song_index]))

similar_songs = sorted(similarity_score, key = lambda x:x[1], reverse = True) 

print('Songs suggested for you : \n')

i = 1

for song in similar_songs:
  year = song[0]
  title_from_index = data_3[data_3.index==year]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1


Songs suggested for you : 

1 . The Cove
2 . Dead And Gone [feat. Justin Timberlake] (Explicit Album Version)
3 . You And Your Heart
4 . The Modern Leper
5 . That Was Just A Dream
6 . I Kissed A Girl
7 . Horchata
8 . Halo
9 . Red To Black (Album Version)
10 . You're The One
11 . Fancy Footwork
12 . Bulgarian  Chicks
13 . I Want Your Love
14 . Hey_ Soul Sister
15 . 16 Candles
16 . Too Much Love
17 . The Arms of Sorrow (Album Version)
18 . I Am The Highway
19 . Take A Chance On Me
20 . Wish I Stayed
21 . Forgive Me
22 . Fall For You
23 . Taxi Cab
24 . Breakeven
25 . It's Tricky
26 . Touch Me In The Morning
27 . Electric Bloom
28 . Blue Orchid
29 . Romantic Rights
